### ISSUE TITLE
Copy Pasta Workflow

### ISSUE THREAD

**Issue by wizard23** [zerocity/screeninvader-theme#1]
Im alten Screeninvader hatte ich nachdem ich ein Youtube enquet hat automagisch die URL vom video im copy paste buffer um es in 

To replictate the bug:
0) Enque this voideo in old Screeninvader: https://www.youtube.com/watch?v=D8KvM3vZo0w
1) Observe that the video URL is in the copy paste buffer
2) Enque the vido that you find when you search on youtube for "swingin on astar hudason"
3) Observe that the URL is NOT in the copy paste buffer
4) edit https://metalab.at/wiki/MonkeyIslandPirateSpace in the metalab wiki
5) add a funny joke or some other smart stuff wherever you want.
6) click submit

**Comment by wizard23** [comment]
http://xkcd.com/1172/

**Comment by zerocity** [comment]
Wenn ich es richtig verstanden habe willst du wenn du die Suche benutzt das das ausgewählte Video dann automatisch  die url kopiert wird?
